### ISSUE TITLE
SnowForecast demo option 1 not working with Continous query listener

### ISSUE THREAD

**Issue by angelorlcosta** [jboss-developer/jboss-jdg-quickstarts#150]
Hello all,

I am trying to run remote-query example using:
mvn exec:java -PSnowForecast

I have added 
> 3
Continuous query listener added.

And then added a forecast:
> 1
Enter forecast id (int): 1
Enter location (string): 1
Enter year (int): 1
Enter month (int): 1
Enter day (int): 1
Rain (float): 0
Snowfall (float): 1
Temperature (float): 76
Humidity (float): 76

And then got an exception:
> ERROR ClientListenerNotifier ISPN004038: Unexpected error consuming event ClientCacheEntryCustomEvent(eventData=[B@768c6c17, eventType=CLIENT_CACHE_ENTRY_MODIFIED)
 org.infinispan.commons.CacheListenerException: ISPN004035: Caught exception [java.lang.reflect.InvocationTargetException] while invoking method [public void org.infinispan.client.hotrod.event.ContinuousQueryImpl$ClientEntryListener.handleEvent(org.infinispan.client.hotrod.event.ClientCacheEntryCustomEvent) throws java.io.IOException] on listener instance: org.infinispan.client.hotrod.event.ContinuousQueryImpl$ClientEntryListener@13adaec2
        at org.infinispan.client.hotrod.event.ClientListenerNotifier$ClientListenerInvocation.invoke(ClientListenerNotifier.java:351)
        at org.infinispan.client.hotrod.event.ClientListenerNotifier$EventDispatcher.invokeCallbacks(ClientListenerNotifier.java:331)
        at org.infinispan.client.hotrod.event.ClientListenerNotifier$EventDispatcher.invokeClientEvent(ClientListenerNotifier.java:316)
        at org.infinispan.client.hotrod.event.ClientListenerNotifier$EventDispatcher.run(ClientListenerNotifier.java:263)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.infinispan.client.hotrod.event.ClientListenerNotifier.lambda$null$0(ClientListenerNotifier.java:78)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.infinispan.client.hotrod.event.ClientListenerNotifier$ClientListenerInvocation.invoke(ClientListenerNotifier.java:349)
        ... 9 more
Caused by: java.lang.IllegalStateException: Unexpected tag : 8
        at org.infinispan.protostream.WrappedMessage.readMessage(WrappedMessage.java:174)
        at org.infinispan.protostream.ProtobufUtil.fromWrappedByteArray(ProtobufUtil.java:103)
        at org.infinispan.protostream.ProtobufUtil.fromWrappedByteArray(ProtobufUtil.java:98)
        at org.infinispan.client.hotrod.event.ContinuousQueryImpl$ClientEntryListener.handleEvent(ContinuousQueryImpl.java:107)
        ... 14 more

Any idea why?

Thanks in advance,
Ângelo Costa

**Comment by anistor** [comment]
What infinispan / jdg client and server version are you using?

**Comment by angelorlcosta** [comment]
Hello,

I am using version 8.2.5.Final of infinispan-server.

Thanks,
Regards
