### ISSUE TITLE
"jboss-remote-query-quickstart" not working

### ISSUE THREAD

**Issue by VigneswaranR** [jboss-developer/jboss-jdg-quickstarts#201]
Hi ,

I am running "jboss-remote-query-quickstart" from STS in debug mode.
After line no 92, i.e remoteCache = cacheManager.getCache(cacheName); , the debug pointer is not moving . and Application hangs and throws following exception.

Please help on this.

ERROR RetryOnFailureOperation ISPN004007: Exception encountered. Retry 10 out of 10
 org.infinispan.client.hotrod.exceptions.TransportException:: Could not fetch transport
	at org.infinispan.client.hotrod.impl.transport.tcp.TcpTransportFactory.borrowTransportFromPool(TcpTransportFactory.java:395)
	at org.infinispan.client.hotrod.impl.transport.tcp.TcpTransportFactory.getTransport(TcpTransportFactory.java:241)
	at org.infinispan.client.hotrod.impl.operations.FaultTolerantPingOperation.getTransport(FaultTolerantPingOperation.java:26)
	at org.infinispan.client.hotrod.impl.operations.RetryOnFailureOperation.execute(RetryOnFailureOperation.java:53)
	at org.infinispan.client.hotrod.impl.RemoteCacheImpl.ping(RemoteCacheImpl.java:490)
	at org.infinispan.client.hotrod.impl.RemoteCacheImpl.resolveCompatibility(RemoteCacheImpl.java:551)
	at org.infinispan.client.hotrod.RemoteCacheManager.createRemoteCache(RemoteCacheManager.java:273)
	at org.infinispan.client.hotrod.RemoteCacheManager.getCache(RemoteCacheManager.java:165)
	at org.infinispan.client.hotrod.RemoteCacheManager.getCache(RemoteCacheManager.java:160)
	at org.jboss.as.quickstarts.datagrid.hotrod.query.SnowForecast.<init>(SnowForecast.java:92)
	at org.jboss.as.quickstarts.datagrid.hotrod.query.SnowForecast.main(SnowForecast.java:232)
Caused by: org.infinispan.client.hotrod.exceptions.TransportException:: Could not connect to server: /127.0.0.1:11222
	at org.infinispan.client.hotrod.impl.transport.tcp.TcpTransport.<init>(TcpTransport.java:78)
	at org.infinispan.client.hotrod.impl.transport.tcp.TransportObjectFactory.makeObject(TransportObjectFactory.java:35)
	at org.infinispan.client.hotrod.impl.transport.tcp.TransportObjectFactory.makeObject(TransportObjectFactory.java:16)
	at infinispan.org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1220)
	at org.infinispan.client.hotrod.impl.transport.tcp.TcpTransportFactory.borrowTransportFromPool(TcpTransportFactory.java:390)
	... 10 more
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:111)
	at org.infinispan.client.hotrod.impl.transport.tcp.TcpTransport.<init>(TcpTransport.java:68)
	... 14 more
Exception in thread "main" org.infinispan.client.hotrod.exceptions.TransportException:: Could not fetch transport
	at org.infinispan.client.hotrod.impl.transport.tcp.TcpTransportFactory.borrowTransportFromPool(TcpTransportFactory.java:395)
	at org.infinispan.client.hotrod.impl.transport.tcp.TcpTransportFactory.getTransport(TcpTransportFactory.java:241)
	at org.infinispan.client.hotrod.impl.operations.FaultTolerantPingOperation.getTransport(FaultTolerantPingOperation.java:26)
	at org.infinispan.client.hotrod.impl.operations.RetryOnFailureOperation.execute(RetryOnFailureOperation.java:53)
	at org.infinispan.client.hotrod.impl.RemoteCacheImpl.ping(RemoteCacheImpl.java:490)
	at org.infinispan.client.hotrod.impl.RemoteCacheImpl.resolveCompatibility(RemoteCacheImpl.java:551)
	at org.infinispan.client.hotrod.RemoteCacheManager.createRemoteCache(RemoteCacheManager.java:273)
	at org.infinispan.client.hotrod.RemoteCacheManager.getCache(RemoteCacheManager.java:165)
	at org.infinispan.client.hotrod.RemoteCacheManager.getCache(RemoteCacheManager.java:160)
	at org.jboss.as.quickstarts.datagrid.hotrod.query.SnowForecast.<init>(SnowForecast.java:92)
	at org.jboss.as.quickstarts.datagrid.hotrod.query.SnowForecast.main(SnowForecast.java:232)
Caused by: org.infinispan.client.hotrod.exceptions.TransportException:: Could not connect to server: /127.0.0.1:11222
	at org.infinispan.client.hotrod.impl.transport.tcp.TcpTransport.<init>(TcpTransport.java:78)
	at org.infinispan.client.hotrod.impl.transport.tcp.TransportObjectFactory.makeObject(TransportObjectFactory.java:35)
	at org.infinispan.client.hotrod.impl.transport.tcp.TransportObjectFactory.makeObject(TransportObjectFactory.java:16)
	at infinispan.org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1220)
	at org.infinispan.client.hotrod.impl.transport.tcp.TcpTransportFactory.borrowTransportFromPool(TcpTransportFactory.java:390)
	... 10 more
Caused by: java.net.ConnectException: Connection refused: no further information
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at sun.nio.ch.SocketAdaptor.connect(SocketAdaptor.java:111)
	at org.infinispan.client.hotrod.impl.transport.tcp.TcpTransport.<init>(TcpTransport.java:68)
	... 14 more

**Comment by VigneswaranR** [comment]
i just discovered that when i run JDG by running standalone.bat, only EAP is running and port 11222 is not

**Comment by galderz** [comment]
If you're using JDG, the best would be to get in touch with our professional support team. You should be able to reach them via access.redhat.com.
